apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: related-giraffe-go 
  janus-idp.io/tekton: related-giraffe-go
  backstage.io/kubernetes-id: related-giraffe-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: related-giraffe-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  