apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: related-giraffe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: related-giraffe-go 
  name: related-giraffe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: related-giraffe-go 
